<?php


namespace Trello\Api;


class Batch extends AbstractApi
{
    /**
     * Base path of batch api
     * @var string
     */
    protected $path = 'batch';

    public $useMethod='get';
    public $usePath='/1/batch';
    public $useParameters;
    public $useRequestHeaders;


    private $list = [];

    public function add(AbstractApi $command){
        if (count($this->list)>=10){
            throw new \Exception('too many items');
        }
        if ($command->useMethod!='get'){
            throw new \Exception('only get methods allowed');
        }
        $this->list[] = $command;
        return $this;
    }

    public function process()
    {
        var_dump($this->list);
        return parent::process(); // TODO: Change the autogenerated stub
    }


}