<?php


namespace Trello\Api;


class Batch extends AbstractApi
{
    private $list = [];

    public function add(AbstractApi $command){
        if (count($this->list)>=10){
            throw new \Exception('too many items');
        }
        $this->list[] = $command;
    }

    public function process()
    {
        var_dump($this->list);
        //return parent::process(); // TODO: Change the autogenerated stub
    }


}